apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-web-app
  template:
    metadata:
      labels:
        app: social-media-web-app
    spec:
      containers:
        - name: social-media-web-app
          image: sandeepadocker/social-media-web-app-pipeline:1.0.0-12
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
