apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-web-app
  labels:
    app: social-media-web-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: social-media-web-app
  template:
    metadata:
      labels:
        app: social-media-web-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5173"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: social-media-web-app
        image: sandeepadocker/social_media_web_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: production
        - name: VITE_API_BASE_URL
          value: "https://api.yourdomain.com"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: cache-volume
          mountPath: /app/node_modules
      volumes:
      - name: cache-volume
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000