apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-web-app
  labels:
    app: social-media-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-web-app
  template:
    metadata:
      labels:
        app: social-media-web-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: social-media-web-app
        image: sandeepadocker/social_media_web_app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000