apiVersion: v1
kind: Service
metadata:
  name: social-media-web-app
  labels:
    app: social-media-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: social-media-web-app